//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masraf.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisi
    {
        public int pid { get; set; }
        public string İsim { get; set; }
        public string Soyisim { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Kullanıcı Kullanıcı { get; set; }
    }
}
